// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/storageos/api-manager/internal/pkg/storageos (interfaces: NodeDeleter)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	types "k8s.io/apimachinery/pkg/types"
	reflect "reflect"
)

// MockNodeDeleter is a mock of NodeDeleter interface
type MockNodeDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockNodeDeleterMockRecorder
}

// MockNodeDeleterMockRecorder is the mock recorder for MockNodeDeleter
type MockNodeDeleterMockRecorder struct {
	mock *MockNodeDeleter
}

// NewMockNodeDeleter creates a new mock instance
func NewMockNodeDeleter(ctrl *gomock.Controller) *MockNodeDeleter {
	mock := &MockNodeDeleter{ctrl: ctrl}
	mock.recorder = &MockNodeDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockNodeDeleter) EXPECT() *MockNodeDeleterMockRecorder {
	return m.recorder
}

// DeleteNode mocks base method
func (m *MockNodeDeleter) DeleteNode(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNode", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNode indicates an expected call of DeleteNode
func (mr *MockNodeDeleterMockRecorder) DeleteNode(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNode", reflect.TypeOf((*MockNodeDeleter)(nil).DeleteNode), arg0, arg1)
}

// NodeNamespacedNames mocks base method
func (m *MockNodeDeleter) NodeNamespacedNames(arg0 context.Context) ([]types.NamespacedName, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NodeNamespacedNames", arg0)
	ret0, _ := ret[0].([]types.NamespacedName)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NodeNamespacedNames indicates an expected call of NodeNamespacedNames
func (mr *MockNodeDeleterMockRecorder) NodeNamespacedNames(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NodeNamespacedNames", reflect.TypeOf((*MockNodeDeleter)(nil).NodeNamespacedNames), arg0)
}
