// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/storageos/api-manager/controllers/node-label (interfaces: NodeLabeller)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	storageos "github.com/storageos/api-manager/internal/pkg/storageos"
	types "k8s.io/apimachinery/pkg/types"
	reflect "reflect"
)

// MockNodeLabeller is a mock of NodeLabeller interface
type MockNodeLabeller struct {
	ctrl     *gomock.Controller
	recorder *MockNodeLabellerMockRecorder
}

// MockNodeLabellerMockRecorder is the mock recorder for MockNodeLabeller
type MockNodeLabellerMockRecorder struct {
	mock *MockNodeLabeller
}

// NewMockNodeLabeller creates a new mock instance
func NewMockNodeLabeller(ctrl *gomock.Controller) *MockNodeLabeller {
	mock := &MockNodeLabeller{ctrl: ctrl}
	mock.recorder = &MockNodeLabellerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockNodeLabeller) EXPECT() *MockNodeLabellerMockRecorder {
	return m.recorder
}

// EnsureNodeLabels mocks base method
func (m *MockNodeLabeller) EnsureNodeLabels(arg0 context.Context, arg1 types.NamespacedName, arg2 map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureNodeLabels", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureNodeLabels indicates an expected call of EnsureNodeLabels
func (mr *MockNodeLabellerMockRecorder) EnsureNodeLabels(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureNodeLabels", reflect.TypeOf((*MockNodeLabeller)(nil).EnsureNodeLabels), arg0, arg1, arg2)
}

// NodeObjects mocks base method
func (m *MockNodeLabeller) NodeObjects(arg0 context.Context) (map[types.NamespacedName]storageos.Object, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NodeObjects", arg0)
	ret0, _ := ret[0].(map[types.NamespacedName]storageos.Object)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NodeObjects indicates an expected call of NodeObjects
func (mr *MockNodeLabellerMockRecorder) NodeObjects(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NodeObjects", reflect.TypeOf((*MockNodeLabeller)(nil).NodeObjects), arg0)
}
